import { StrategyEstimateSummary, ProjectTask } from './calculator';
import { ModelData, StrategyLevel, STRATEGY_CONFIG } from './constants';

export function generateScopeBrief(
  projectName: string,
  projectDescription: string,
  activeEstimate: StrategyEstimateSummary,
  models: Record<string, ModelData>
): string {
  const strategy = STRATEGY_CONFIG[activeEstimate.strategy];
  
  let markdown = `# Scope.ai Technical Brief: ${projectName || 'Untitled Project'}\n\n`;
  markdown += `## Project Overview\n${projectDescription || 'No description provided.'}\n\n`;
  
  markdown += `## Strategy: ${strategy.name}\n`;
  markdown += `> ${strategy.description}\n\n`;
  
  markdown += `### Execution Metadata\n`;
  markdown += `- **Total Estimated Cost:** $${activeEstimate.totalCost.toFixed(2)}\n`;
  markdown += `- **Confidence Score:** ${Math.round(activeEstimate.avgConfidence)}%\n`;
  markdown += `- **Velocity Profile:** ${activeEstimate.avgLatency < 2 ? 'High (Near-instant)' : activeEstimate.avgLatency < 4 ? 'Medium (Standard processing)' : 'Low (Deep reasoning)'}\n`;
  markdown += `- **Total Compute Turns:** ${activeEstimate.totalTurns}\n\n`;
  
  markdown += `## Model Routing Playbook\n`;
  markdown += `This table defines which models should be used for each task type to maintain the ${strategy.name} strategy.\n\n`;
  
  markdown += `| Task | Complexity | Recommended Model | Reasoning Tier | Cost (Est) |\n`;
  markdown += `| :--- | :--- | :--- | :--- | :--- |\n`;
  
  activeEstimate.tasks.forEach(data => {
    const model = models[data.appliedModel];
    markdown += `| ${data.task.name} | ${data.task.complexity.toUpperCase()} | ${model?.name || data.appliedModel} | ${data.reasoningScore}/10 | $${data.cost.toFixed(2)} |\n`;
  });
  
  markdown += `\n---\n`;
  markdown += `*Generated by Scope.ai - The Pre-Flight Optimizer for Agentic Workflows.*`;
  
  return markdown;
}

// Maps OpenRouter models to Claude Code native strings
const CLAUDE_CODE_MODELS: Record<string, string> = {
  'anthropic/claude-3.5-sonnet': 'claude-3-5-sonnet-20241022',
  'anthropic/claude-3-5-haiku': 'claude-3-5-haiku-20241022',
  'anthropic/claude-3-haiku': 'claude-3-haiku-20240307',
  'anthropic/claude-3-opus': 'claude-3-opus-20240229',
};

export function generateExecutionScript(
  projectName: string,
  projectDescription: string,
  activeEstimate: StrategyEstimateSummary,
  models: Record<string, ModelData>
): string {
  const strategy = STRATEGY_CONFIG[activeEstimate.strategy];
  
  let script = `#!/bin/bash\n`;
  script += `# ==========================================\n`;
  script += `# Scope.ai Execution Playbook: ${projectName || 'Untitled Project'}\n`;
  script += `# Strategy: ${strategy.name}\n`;
  script += `# Estimated Cost: $${activeEstimate.totalCost.toFixed(2)}\n`;
  script += `# ==========================================\n`;
  script += `# Description: ${projectDescription.replace(/\n/g, ' ')}\n\n`;
  
  script += `echo "🚀 Starting Scope.ai Agentic Workflow..."\n`;
  script += `echo "Strategy: ${strategy.name} | Total Tasks: ${activeEstimate.tasks.length}"\n\n`;

  activeEstimate.tasks.forEach((data, index) => {
    const model = models[data.appliedModel];
    // Attempt to map to Claude Code, fallback to generic prompt flag
    const claudeModel = CLAUDE_CODE_MODELS[data.appliedModel] || 'claude-3-5-sonnet-20241022';
    
    script += `# --- Task ${index + 1}: ${data.task.name} (${data.task.complexity.toUpperCase()}) ---\n`;
    script += `# Target Model: ${model?.name || data.appliedModel}\n`;
    script += `echo "⏳ Executing Task ${index + 1}: ${data.task.name}..."\n`;
    script += `claude -m ${claudeModel} -p "Execute the following task: ${data.task.name}. Ensure you refer to the project description: ${projectDescription.replace(/\n/g, ' ')}"\n`;
    script += `echo "✅ Completed: ${data.task.name}\\n"\n\n`;
  });

  script += `echo "🎉 All tasks executed successfully."\n`;
  
  return script;
}

export function downloadFile(filename: string, content: string) {
  const element = document.createElement('a');
  const file = new Blob([content], {type: 'text/plain'});
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}
